apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-deployment
  namespace: kubapp
  labels:
    app: kub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kub
  template:
    metadata:
      labels:
        app: kub
    spec:
      containers:
        - name: kub
          image: dannekun/exam-kub:0.0.1
          imagePullPolicy: IfNotPresent