apiVersion: v1
kind: Service
metadata:
  name: kub-service
  namespace: kubapp
spec:
  selector:
    app: kub
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP